// GENERATED by scripts/sync-function-shared.mjs from packages/shared/src/notifications.ts.
// Do not edit. Change the source and run `npm run functions:sync`; a test fails otherwise.

// Deno cannot follow the source's extensionless import, and a status the database stores
// is a string anyway. The source keeps the precise union for the apps.
type OrderStatus = string;

/**
 * Notification content is derived from order state, in one place, so in-app
 * notifications and (later) push notifications never drift apart.
 */
export type NotificationAudience = 'student' | 'canteen' | 'delivery';

export type NotificationContent = {
  title: string;
  body: string;
};

export type OrderNotificationContext = {
  orderCode: string;
  canteenName: string;
  hostelLabel: string;
};

type Builder = (ctx: OrderNotificationContext) => NotificationContent;

const STUDENT: Partial<Record<OrderStatus, Builder>> = {
  pending: (c) => ({
    title: 'Order placed',
    body: `${c.canteenName} has your order ${c.orderCode}.`,
  }),
  accepted: (c) => ({
    title: 'Order accepted',
    body: `${c.canteenName} is starting on ${c.orderCode}.`,
  }),
  preparing: (c) => ({
    title: 'Being prepared',
    body: `Your food for ${c.orderCode} is on the stove.`,
  }),
  ready: () => ({ title: 'Ready for pickup', body: 'Waiting for a delivery partner.' }),
  assigned: () => ({ title: 'Partner assigned', body: 'A partner is heading to the canteen.' }),
  picked_up: (c) => ({ title: 'On the way', body: `Your food is heading to ${c.hostelLabel}.` }),
  delivered: (c) => ({ title: 'Delivered', body: `Enjoy! Rate ${c.orderCode} to help others.` }),
  cancelled: (c) => ({ title: 'Order cancelled', body: `${c.orderCode} was cancelled.` }),
  rejected: (c) => ({
    title: 'Order rejected',
    body: `${c.canteenName} could not take ${c.orderCode}.`,
  }),
};

const CANTEEN: Partial<Record<OrderStatus, Builder>> = {
  pending: (c) => ({ title: 'New order', body: `${c.orderCode} needs accepting.` }),
  cancelled: (c) => ({
    title: 'Order cancelled',
    body: `${c.orderCode} was cancelled. Stop preparing it.`,
  }),
};

const DELIVERY: Partial<Record<OrderStatus, Builder>> = {
  ready: (c) => ({
    title: 'Delivery available',
    body: `${c.orderCode} at ${c.canteenName} → ${c.hostelLabel}.`,
  }),
  cancelled: (c) => ({ title: 'Delivery cancelled', body: `${c.orderCode} is no longer active.` }),
};

const BY_AUDIENCE: Record<NotificationAudience, Partial<Record<OrderStatus, Builder>>> = {
  student: STUDENT,
  canteen: CANTEEN,
  delivery: DELIVERY,
};

/**
 * The order fields both surfaces read, with the same fallbacks.
 *
 * The inbox and push each build a context from an order row, so the fallbacks live here
 * rather than in either: an order the reader can no longer see (RLS returns the embed as
 * null) reads "your order" on the phone's lock screen exactly as it does in the inbox.
 */
export function notificationContext(
  order: {
    code?: string | null;
    canteen_name_snapshot?: string | null;
    hostel_label?: string | null;
  } | null,
): OrderNotificationContext {
  return {
    orderCode: order?.code ?? 'your order',
    canteenName: order?.canteen_name_snapshot ?? 'the canteen',
    hostelLabel: order?.hostel_label ?? 'your room',
  };
}

/**
 * The Android notification channel every order push goes to.
 *
 * The app creates it and `send-push` addresses it, so the id is written once. Android
 * files a push naming a channel that does not exist under a silent default, which looks
 * exactly like "push works but never makes a sound".
 */
export const PUSH_CHANNEL = { id: 'orders', name: 'Order updates' } as const;

/** Returns null when this audience should not be notified about this status. */
export function orderNotification(
  audience: NotificationAudience,
  status: OrderStatus,
  ctx: OrderNotificationContext,
): NotificationContent | null {
  return BY_AUDIENCE[audience][status]?.(ctx) ?? null;
}
